export const datas=
    [
        {
          "city": "Conakry", 
          "lat": "9.5092", 
          "lng": "-13.7122", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Conakry", 
          "capital": "primary", 
          "population": "1667864", 
          "population_proper": "1667864"
        }, 
        {
          "city": "Guéckédou", 
          "lat": "8.5667", 
          "lng": "-10.1333", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "N’Zérékoré", 
          "capital": "minor", 
          "population": "221715", 
          "population_proper": "221715"
        }, 
        {
          "city": "Siguiri", 
          "lat": "11.4189", 
          "lng": "-9.1644", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Kankan", 
          "capital": "minor", 
          "population": "183875", 
          "population_proper": "183875"
        }, 
        {
          "city": "N’Zérékoré", 
          "lat": "7.7600", 
          "lng": "-8.8300", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "N’Zérékoré", 
          "capital": "admin", 
          "population": "168121", 
          "population_proper": "132728"
        }, 
        {
          "city": "Kindia", 
          "lat": "10.0600", 
          "lng": "-12.8700", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Kindia", 
          "capital": "admin", 
          "population": "117062", 
          "population_proper": "69960"
        }, 
        {
          "city": "Boké", 
          "lat": "10.9400", 
          "lng": "-14.3000", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Boké", 
          "capital": "admin", 
          "population": "116270", 
          "population_proper": "116270"
        }, 
        {
          "city": "Kankan", 
          "lat": "10.3900", 
          "lng": "-9.3100", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Kankan", 
          "capital": "admin", 
          "population": "114009", 
          "population_proper": "106906"
        }, 
        {
          "city": "Labé", 
          "lat": "11.3167", 
          "lng": "-12.2833", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Labé", 
          "capital": "admin", 
          "population": "107695", 
          "population_proper": "107695"
        }, 
        {
          "city": "Mamou", 
          "lat": "10.3736", 
          "lng": "-12.0847", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Mamou", 
          "capital": "admin", 
          "population": "71153", 
          "population_proper": "41619"
        }, 
        {
          "city": "Kamsar", 
          "lat": "10.6500", 
          "lng": "-14.6167", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Boké", 
          "capital": "", 
          "population": "68999", 
          "population_proper": "68999"
        }, 
        {
          "city": "Kissidougou", 
          "lat": "9.1905", 
          "lng": "-10.1200", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Faranah", 
          "capital": "minor", 
          "population": "66815", 
          "population_proper": "47099"
        }, 
        {
          "city": "Macenta", 
          "lat": "8.5504", 
          "lng": "-9.4800", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "N’Zérékoré", 
          "capital": "minor", 
          "population": "43102", 
          "population_proper": "41233"
        }, 
        {
          "city": "Dabola", 
          "lat": "10.7500", 
          "lng": "-11.1167", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Faranah", 
          "capital": "minor", 
          "population": "38617", 
          "population_proper": "38617"
        }, 
        {
          "city": "Télimélé", 
          "lat": "10.9050", 
          "lng": "-13.0430", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Kindia", 
          "capital": "minor", 
          "population": "30311", 
          "population_proper": "30311"
        }, 
        {
          "city": "Tougué", 
          "lat": "11.4400", 
          "lng": "-11.6700", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Labé", 
          "capital": "minor", 
          "population": "25531", 
          "population_proper": "25531"
        }, 
        {
          "city": "Fria", 
          "lat": "10.3804", 
          "lng": "-13.5500", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Boké", 
          "capital": "minor", 
          "population": "23729", 
          "population_proper": "23729"
        }, 
        {
          "city": "Pita", 
          "lat": "11.0800", 
          "lng": "-12.4010", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Mamou", 
          "capital": "minor", 
          "population": "20052", 
          "population_proper": "20052"
        }, 
        {
          "city": "Faranah", 
          "lat": "10.0404", 
          "lng": "-10.7500", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Faranah", 
          "capital": "admin", 
          "population": "19469", 
          "population_proper": "9350"
        }, 
        {
          "city": "Kérouané", 
          "lat": "9.2704", 
          "lng": "-9.0200", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Kankan", 
          "capital": "minor", 
          "population": "15406", 
          "population_proper": "7228"
        }, 
        {
          "city": "Kouroussa", 
          "lat": "10.6530", 
          "lng": "-9.8920", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Kankan", 
          "capital": "minor", 
          "population": "14223", 
          "population_proper": "14223"
        }, 
        {
          "city": "Koundara", 
          "lat": "12.4800", 
          "lng": "-13.2960", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Boké", 
          "capital": "minor", 
          "population": "13990", 
          "population_proper": "13990"
        }, 
        {
          "city": "Beyla", 
          "lat": "8.6870", 
          "lng": "-8.6570", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "N’Zérékoré", 
          "capital": "minor", 
          "population": "13204", 
          "population_proper": "13204"
        }, 
        {
          "city": "Forécariah", 
          "lat": "9.4300", 
          "lng": "-13.0980", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Kindia", 
          "capital": "minor", 
          "population": "12358", 
          "population_proper": "12358"
        }, 
        {
          "city": "Gaoual", 
          "lat": "11.7540", 
          "lng": "-13.2130", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Boké", 
          "capital": "minor", 
          "population": "7461", 
          "population_proper": "7461"
        }, 
        {
          "city": "Dalaba", 
          "lat": "10.6560", 
          "lng": "-12.2720", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Mamou", 
          "capital": "minor", 
          "population": "6349", 
          "population_proper": "6349"
        }, 
        {
          "city": "Dinguiraye", 
          "lat": "11.2990", 
          "lng": "-10.7260", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Faranah", 
          "capital": "minor", 
          "population": "6062", 
          "population_proper": "6062"
        }, 
        {
          "city": "Mali", 
          "lat": "12.0840", 
          "lng": "-12.3010", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Labé", 
          "capital": "minor", 
          "population": "5479", 
          "population_proper": "5479"
        }, 
        {
          "city": "Yomou", 
          "lat": "7.5660", 
          "lng": "-9.2533", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "N’Zérékoré", 
          "capital": "minor", 
          "population": "3614", 
          "population_proper": "1601"
        }, 
        {
          "city": "Boffa", 
          "lat": "10.1850", 
          "lng": "-14.0430", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Boké", 
          "capital": "minor", 
          "population": "2332", 
          "population_proper": "2332"
        }, 
        {
          "city": "Coyah", 
          "lat": "9.7056", 
          "lng": "-13.3769", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Kindia", 
          "capital": "minor", 
          "population": "", 
          "population_proper": ""
        }, 
        {
          "city": "Dubréka", 
          "lat": "9.7911", 
          "lng": "-13.5233", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Kindia", 
          "capital": "minor", 
          "population": "", 
          "population_proper": ""
        }, 
        {
          "city": "Lola", 
          "lat": "7.8000", 
          "lng": "-8.5333", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "N’Zérékoré", 
          "capital": "minor", 
          "population": "", 
          "population_proper": ""
        }, 
        {
          "city": "Koubia", 
          "lat": "11.5833", 
          "lng": "-11.9000", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Labé", 
          "capital": "minor", 
          "population": "", 
          "population_proper": ""
        }, 
        {
          "city": "Mandiana", 
          "lat": "10.6333", 
          "lng": "-8.6833", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Kankan", 
          "capital": "minor", 
          "population": "", 
          "population_proper": ""
        }, 
        {
          "city": "Lélouma", 
          "lat": "11.1833", 
          "lng": "-12.9333", 
          "country": "Guinea", 
          "iso2": "GN", 
          "admin_name": "Labé", 
          "capital": "minor", 
          "population": "", 
          "population_proper": ""
        }
      ]
